config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#home'
  resources :countries do
    resources :cities

  end
resources :articles
get '/admin_panel', to: 'welcome#admin_panel', as: :admin_panel
get '/country_articles', to: 'countries#articles_by_country', as: :articles_country
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
belongs_to :city

end

app/models/city.rb
class City < ApplicationRecord
  validates :ciudad, uniqueness: true
  has_many :articles

end

app/models/country.rb
class Country < ApplicationRecord
has_many :cities, dependent: :destroy
has_many :articles, through: :cities
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
    @article = Article.new
  end

  def index
    @articles = Article.all
  end

  def show
    load_article
  end

  def create
    article = Article.new(article_params)
    if article.save!
      message =  {success: 'Your article was created'}
    else
      message =  {success: article.errors.full_messages.to_sentence}
    end
    redirect_to new_article_path, flash: message
  end

  def update
    load_article
    @article.update(article_params)
    redirect_to edit_article_path(@article), flash: {success: 'Your article was updated'}
  end

  def destroy
    load_article
    @article.destroy
    redirect_to articles_path, flash: {success: 'Your article was deleted'}
  end

  def edit
    load_article
  end


  private

  def article_params
    params.require(:article).permit(:title, :city_id, :experiencia, :fecha, :autor)


  end


  def load_article
    @article = Article.find(params[:id])
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  def new
    @city = City.new
    @country = Country.find(params[:country_id])
  end

  def index
    @country = Country.find(params[:country_id])
    @cities = @country.cities
  end

  def show
    @country = Country.find(params[:country_id])
    @cities = City.find(params[:id])
  end

  def create
    @country = Country.find(params[:country_id])
    new_city = @country.cities.new(city_params)
    if new_city.save
      redirect_to country_path(@country, @city)
    else
      redirect_to country_path(@country, @city), flash: {warning: new_city.errors.full_messages.to_sentence }
    end

  end


  def update
    load_city
    @country = Country.find(params[:country_id])
    @city.update(city_params)
    redirect_to edit_country_city_path(@country, @city), flash: {success: 'Ciudad fue actualizado'}
  end

  def destroy
    load_city
    load_country
    @city.destroy
    redirect_to country_cities_path(@country), flash: {success: 'Pais fue eliminado'}
  end

  def edit
    load_city
    @country = Country.find(params[:country_id])

  end


  private

  def city_params
    params.require(:city).permit(:ciudad, :county_id, :continente, :poblacion, :descripcion,)
  end

  def load_country
    @country = Country.find(params[:country_id])
  end

  def load_city
    @city = City.find(params[:id])
  end
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController

  def new
    @country = Country.new
  end

  def index
    @countries = Country.all
  end

  def show
    load_country
  end

  def create
    country = Country.new(country_params)
    if country.save
      message =  {success: 'Pais fue creado'}
    else
      message =  {success: pais.errors.full_messages.to_sentence}
    end
    redirect_to new_country_path, flash: message
  end

  def update
    load_country
    @country.update(country_params)
    redirect_to edit_country_path(@country), flash: {success: 'Pais fue actualizado'}
  end

  def destroy
    load_country
    @country.destroy
    redirect_to countries_path, flash: {success: 'Pais fue eliminado'}
  end

  def edit
    load_country

  end

  def articles_by_country
    @countries = Country.where(continente: params[:continente])
  end

  private

  def country_params
    params.require(:country).permit(:continente, :pais, :poblacion,:vida_costo, :vacaciones_costo, :moneda,:descripcion, :visa_requiere, :lgtb_amigable)
  end

  def load_country

    @country = Country.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
    @articles = Article.all.order('fecha desc').limit(4)
  end

  def admin_panel
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |form| %>
  Titulo: <%= form.text_field:title%><br />
  ciudad_id:<%= form.select :city_id, City.all.collect {|city| [ city.ciudad, city.id.to_s ] } %><br />
  Experienca: <%= form.text_area :experiencia%><br />
  fecha:<%= form.date_field :fecha %><br />
  Autor: <%= form.text_field :autor%><br />




  <%= form.submit %>
<% end %>

app/views/articles/edit.html.erb
<h1>Update <%= @article.title.capitalize %></h1>
<%= render 'form' %>

<body>
  <% if flash[:success] %>
    <div class="success"><%= flash[:success] %></div>
  <% end %>

app/views/articles/index.html.erb
<h1>Lista de Articulos</h1>

<ol>
<% @articles.each do |article| %>
  <li>

    <%= article.title.capitalize%>

    <%= link_to 'Info', article_path(article) %>
    <%= link_to 'Update info', edit_article_path(article) %>
    <%= link_to 'Delete', article_path(article), method: :delete %>
  </li>
<% end %>
</ol>



<h3>Links</h3>
<ul>
<li>
    <%= link_to 'Crear un articulo', new_article_path %>
</li>

</ul>

app/views/articles/new.html.erb
<h1>Crear nuevo articulo</h1>
<%= render 'form' %>

<% if flash[:success] %>
  <div class="success"><%= flash[:success] %></div>
<% end %>

app/views/articles/show.html.erb
<h1>Articulo</h1>


<ul>


<li>Titulo: <%= @article.title%></li>
<li>Ciudad: <%= @article.city.ciudad%></li>
<li>Experiencia: <%= @article.experiencia%></li>
<li>fecha: <%= @article.fecha%></li>
<li>Autor: <%= @article.autor%></li>




</ul>

app/views/cities/_form.html.erb
<%= form_for [@country, @city] do |form| %>
  Ciudad:<%= form.text_field :ciudad %><br />
  poblacion:<%= form.text_field :poblacion %><br />
  Descripcion: <%= form.text_field :descripcion %><br />



  <%= form.submit %>
<% end %>

app/views/cities/destroy.html.erb
<h1>Destroy a city</h1>
<%= @city.ciudad %></h1>
<%= render 'form' %>

app/views/cities/edit.html.erb
<h1>Update <%= @city.ciudad %></h1>
<%= render 'form' %>
<% if flash[:success] %>
  <div class="success"><%= flash[:success] %></div>
<% end %>

app/views/cities/index.html.erb
<h1>Lista de Ciudades visitados</h1>
<table class="table">
  <thead class="thead-dark">

      <tr>
        <th scope="col">Ciudad</th>
        <th scope="col">country ID</th>
        <th scope="col">Continente</th>
        <th scope="col">poblacion</th>
        <th scope="col">Descripcion</th>


    </thead>

  <% @cities.each do |city| %>

    <tr>
      <td><%= city.ciudad.capitalize %></td>
      <td><%= city.country_id %></td>
      <td><%= city.continente %></td>
      <td><%= city.poblacion %></td>
      <td><%= city.descripcion %></td>
      <td><%= link_to 'Actualizar', edit_country_city_path(@country,city), class: "btn btn-success" %></td>
      <td><%= link_to 'Eliminar', country_city_path(@country,city), method: :delete, class: "btn btn-danger" %></td>




    <tr>
  <% end %>

  <table>

app/views/cities/new.html.erb
<h1>Crear nueva ciudad visitado</h1>
<%= render 'form' %>
<% if flash[:success] %>
  <div class="success"><%= flash[:success] %></div>
<% end %>

app/views/cities/show.html.erb
<h1>Ciudades</h1>


<td>Ciudad: <%= city.city.capitalize %></td>
<td>country_id: <%= city.country_id %></td>
<td>Continente: <%= city.continente %></td>
<td>Poblacion: <%= city.poblacion %></td>
<td>Descripcion <%= city.descripcion %></td>

app/views/countries/_form.html.erb
<%= form_for @country do |form| %>

  Continente:<%= form.select :continente, [['Europa', 'Europa'], ['Oceania','Oceania'], ['India', 'India'], ['Sureste Asiatico','Sureste Asiatico'], ['America','America']] %><br />
  Pais: <%= form.text_field :pais %><br />
  Poblacion: <%= form.text_field :poblacion %><br />
  Costo de Vida:<%= form.select :vida_costo, [['Alto Alto', 'Alto Alto'], ['Alto Medio','Alto Medio'], ['Medio Medio', 'Medio Medio'], ['Medio Bajo','Medio Bajo'], ['Bajo','Bajo']]  %><br />
  Costo de Vacaciones: <%= form.select :vacaciones_costo, [['Entre 5$ y 15$ por dia', 'Entre 5$ y 15$ por dia'], ['Entre 16$ y 25$ por dia' ,'Entre 26$ y 35$ por dia'], ['Entre 36$ y 45$ por dia','Entre 36$ y 45$ por dia'], ['Mas de 46$ por dia','Mas de 46$ por dia']]%><br />
  Moneda: <%= form.text_field :moneda %><br />
  Descripcion:<%= form.text_area :descripcion %><br />
  Requiere visa: <%= form.text_area :visa_requiere %><br />
  LGTB AMIGABLE: <%= form.text_area :lgtb_amigable %><br />


  <%= form.submit %>
<% end %>

app/views/countries/articles_by_country.html.erb
<ol>
<% @countries.each do |country| %>
  <% country.articles.each do |article| %>
    <li>

      <%= article.title.capitalize%>

      <%= link_to 'Info', article_path(article) %>
      <%= link_to 'Update info', edit_article_path(article) %>
      <%= link_to 'Delete', article_path(article), method: :delete %>
    </li>
  <% end %>
<% end %>
</ol>

app/views/countries/destroy.html.erb
<h1>Destroy a country</h1>
<%= @country.pais %></h1>
<%= render 'form' %>

app/views/countries/edit.html.erb
<h1>Update <%= @country.pais %></h1>
<%= render 'form' %>
<% if flash[:success] %>
  <div class="success"><%= flash[:success] %></div>
<% end %>

app/views/countries/index.html.erb
<h1>Lista de Paises visitados</h1>
<table class="table">
  <thead class="thead-dark">



      <tr>
        <th scope="col">Continente</th>
        <th scope="col">Pais</th>
        <th scope="col">Poblacion</th>
        <th scope="col">Costo de vida</th>
        <th scope="col">Costo de vacaciones</th>
        <th scope="col">Moneda</th>
        <th scope="col">Descripcion</th>
        <th scope="col">Requiere Visa</th>
        <th scope="col">LGTB Amigable</th>
        <th scope="col">Funcionalidades</th>



    </thead>

  <% @countries.each do |country| %>

    <tr>
      <td><%= country.continente.capitalize %></td>
      <td><%= country.pais %></td>
      <td><%= country.poblacion %></td>
      <td><%= country.vida_costo %></td>
      <td><%= country.vacaciones_costo %></td>
      <td><%= country.moneda %></td>
      <td><%= country.descripcion %></td>
      <td><%= country.visa_requiere %></td>
      <td><%= country.lgtb_amigable %></td>
      <td><%= link_to 'Actualizar', edit_country_path(country), class: "d-block m-1 btn btn-info" %>
      <%= link_to 'Cities', country_cities_path(country), class: "d-block m-1 btn btn-success" %>
      <%= link_to 'Eliminar', country_path(country), method: :delete, class: "d-block m-1 btn btn-danger" %>
      <%= link_to 'Agregar Ciudad', new_country_city_path(country), class: "d-block m-1  btn btn-primary"%></td>



    <tr>
  <% end %>

  <table>

app/views/countries/new.html.erb
<h1>Crear nuevo pais visitado</h1>
<%= render 'form' %>

app/views/countries/show.html.erb
<% if flash[:warning] %>
  <div class="success"><%= flash[:warning] %></div>
<% end %>
<h1>Paises</h1>


<td>Continente: <%= @country.continente %></td>
<td>Pais: <%= @country.pais %></td>
<td>Poblacion: <%= @country.poblacion %></td>
<td>Costo de Vida: <%= @country.vida_costo %></td>
<td>Costo de Vacaciones: <%= @country.vacaciones_costo %></td>
<td>Moneda: <%= @country.moneda %></td>
<td>Descripcion: <%= @country.vida_costo %></td>
<td>Visa Requerida: <%= @country.visa_requiere %></td>
<td>LGTB Amigable: <%= @country.lgtb_amigable %></td>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/admin_panel.erb
<h2>Funcionalidades de Administrador<h2>


<td><%= link_to 'Agregar Pais', new_country_path%></td>
<td><%= link_to 'Ver Paises', countries_path%></td>
<td><%= link_to 'Agregar Articulos', new_article_path %></td>
<td><%= link_to 'Ver Articulos', articles_path%></td>

app/views/welcome/home.html.erb
<div class="container">
  <header class="blog-header py-3">
    <div class="row flex-nowrap justify-content-between align-items-center">
      <div class="col-4 pt-1">
        <a class="text-muted" href="/users/sign_up">Subscribete</a>
      </div>
      <!-- /<div class="col-4 text-center">
        <a class="blog-header-logo text-dark" href="#">COLOMBIANO VIAJANDO POR EL MUNDO</a>
      </div> -->
      <div class="col-4 d-flex justify-content-end align-items-center">
        <a class="text-muted" href="#">
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="mx-3" role="img" viewBox="0 0 24 24" focusable="false"><title>Search</title><circle cx="10.5" cy="10.5" r="7.5"></circle><path d="M21 21l-5.2-5.2"></path></svg>
        </a>
        <% if user_signed_in? %>
          <%= link_to 'log out', destroy_user_session_path, method: :delete %>
        <% else %>
          <a class="btn btn-sm btn-outline-secondary" href="/users/sign_in">Entrar</a>
        <% end %>
      </div>
    </div>
  </header>

  <% if current_user && current_user.is_admin %>

<%= link_to'/admin_panel' do %>


        <img src="https://st.depositphotos.com/1742172/4644/v/950/depositphotos_46442571-stock-illustration-cartoon-padlock-and-key.jpg" alt="" width="45px">
      <% end %>


  <% end %>



  <div class="nav-scroller py-1 mb-2">



    <nav class="nav d-flex justify-content-between">
      <a class="p-2 text-muted" href="<%= articles_country_path(continente: 'Europa')%>">Europa</a>
      <a class="p-2 text-muted" href="<%= articles_country_path(continente: 'Oceania')%>">Oceania</a>
      <a class="p-2 text-muted" href="<%= articles_country_path(continente: 'Sureste Asiatico')%>">Sureste Asiatico</a>
      <a class="p-2 text-muted" href="<%= articles_country_path(continente: 'India')%>">India</a>
      <a class="p-2 text-muted" href="<%= articles_country_path(continente: 'America') %>">America</a>

    </nav>
  </div>

  <div class="jumbotron p-4 p-md-5 text-white rounded bg-dark d-flex" >
    <div class="col-md-6 px-0">
      <h1 class="display-4 font-italic">Forma facil de como estudiar en el exterior</h1>
      <p class="lead my-3">Mi historia empezo en el 2015, cuando estaba terminando mi pregrado, nunca habia pensado la forma de vivir en el exterior por que sencillamente contaba con todo lo necesario para llevar una buena vida en mi pais.</p>
      <p class="lead mb-0"><a href="#" class="text-white font-weight-bold">Continuar leyendo...</a></p>
    </div>



  <div class="row">
    <div class="col-md-12">
      <div class="media">
      <%= image_tag  'sydneyprincipal.jpg', class: 'w-100' %>
      </div>
    </div>
</div>
  </div>





  <div class="row mb-2">
    <div class="col-md-6">
      <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-primary">Concejos</strong>
          <h3 class="mb-0">Aprender otro idioma</h3>
          <div class="mb-1 text-muted">Jul 09</div>
          <p class="card-text mb-auto">Como aprender ingles de una forma divertida y rapida.</p>
          <a href="#" class="stretched-link">Continue reading</a>
        </div>

<img class="irc_mi" src="https://www.modoemprendedor.com/wp-content/uploads/7-te%CC%81cnicas-para-aprender-otro-idioma-ma%CC%81s-ra%CC%81pido-que-el-promedio..png" onload="typeof google==='object'&amp;&amp;google.aft&amp;&amp;google.aft(this)" width="284" height="180" style="margin-top: 0px;" data-iml="1562774884145" alt="Image result for aprendiendo otro idioma">


      </div>
    </div>
    <div class="col-md-6">
      <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-success">Colombianos a viajar</strong>
          <h3 class="mb-0">Viajando sin visas</h3>
          <div class="mb-1 text-muted">Julio 09</div>
          <p class="mb-auto">Conoce los lugares donde visitar sin visa y aprovecha tu pasaporte, sin tramites.</p>
          <a href="#" class="stretched-link">Continuar leyendo</a>
        </div>

<img class="irc_mi" src="https://static.iris.net.co/semana/upload/images/2015/7/21/435653_162634_1.jpg" onload="typeof google==='object'&amp;&amp;google.aft&amp;&amp;google.aft(this)" width="284" height="220" style="margin-top: 0px;" data-iml="1562775397522" alt="Image result for pasaporte colombiano">


      </div>
    </div>
  </div>
</div>


<main role="main" class="container">
  <div class="row">
    <div class="col-md-8 blog-main">
      <h3 class="pb-4 mb-4 font-italic border-bottom">
        Entradas recientes
      </h3>
      <% @articles.each do |article| %>
        <div class="blog-post">
          <h2 class="blog-post-title"> <%= article.title.capitalize %></h2>
          <p class="blog-post-meta"> <%= article.city.ciudad %></p>

          <p> <%= article.experiencia.truncate(220) %></p>
          <a href="<%= article_path(article) %>" class="stretched-link">Continuar leyendo</a>
        </div><!-- /.blog-post -->
      <% end %>



      <nav class="blog-pagination">
        <a class="btn btn-outline-primary" href="#">Older</a>
        <a class="btn btn-outline-secondary disabled" href="#" tabindex="-1" aria-disabled="true">Newer</a>
      </nav>

    </div><!-- /.blog-main -->

    <aside class="col-md-4 blog-sidebar">
      <div class="p-4 mb-3 bg-light rounded">

        <div class="media" >
        <%= image_tag  'andresblog.jpg', class: 'w-100 rounded-circle' %>



        </div>


        <h4 class="font-italic" >Acerca de mi</h4>


        <p class="mb-0">Desde ya hace algunos años deje mi trabajo y todo lo que tenia en mi pais de origen el cual es Colombia, con el fin de aprender nuevas cosas, conocer nuevas culturas e integrarme a un movimiento de vieajeros independientes, en Noviembre del 2015 algunas semanas después de graduarme como Mercadologo de la Universidad Libre de Cali, empecé mi busqueda entre las opciones que tenia para irme a estudiar fuera del pais, en ese tiempo mi nivel de ingles era casi nulo, cosa que no me detuvieron para viajar, desde hace mas de 3 años estoy viviendo en el exterior, y conozco de mucha gente que como yo ama viajar, en este blog los quiero dar algunos concejos para que hagan realidad esos sueños .</p>
      </div>

      <div class="p-4">
        <h4 class="font-italic">Archivos</h4>
        <ol class="list-unstyled mb-0">
          <li><a href="#">2019</a></li>
          <li><a href="#">2018</a></li>
          <li><a href="#">2017</a></li>
          <li><a href="#">2016</a></li>
          <li><a href="#">2015</a></li>
          <li><a href="#">2014</a></li>
          <li><a href="#">2013</a></li>

        </ol>
      </div>

      <div class="p-4">
        <h4 class="font-italic">Encuentranos</h4>
        <ol class="list-unstyled">
          <li><a href="https://wwww.github.com/luja31922">GitHub</a></li>
          <li><a href="https://wwww.instagram.com/lujanandres22/">Instagram</a></li>
          <li><a href="https://wwww.facebook.com/luja31922">Facebook</a></li>





        </ol>
      </div>
    </aside><!-- /.blog-sidebar -->

  </div><!-- /.row -->

</main>